### ISSUE TITLE
openBrowser() error not handled gracefully

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [CSE-25/amrita_pyq#14]
## Description
This section of the code has an irrecoverable crash with the `exec` command. Ideally, it should be returning an `error` that needs to be handled gracefully and not crash the entire program.

## Screenshots
![image](https://github.com/user-attachments/assets/296fc533-34d3-4a8f-9c31-a5b79c4f4398)

## Tagging Maintainers
@Ashrockzzz2003 @Abhinav-ark

**Comment by Nandgopal-R** [comment]
Can I work on this?

**Comment by Ashrockzzz2003** [comment]
Yes @Nandgopal-R 
Assigning this to you
You have time until `January 2, 2025` to come up with a PR.
