### ISSUE TITLE
Add `DOCUMENTATION` on how to use this tool.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [CSE-25/amrita_pyq#3]
- [ ] Documentation on using the tool.
- [ ] Documentation for OSS formats.

**Comment by RD-Tarun** [comment]
Hi, I'd like to handle this issue please, @Ashrockzzz2003 kindly give me permissions

**Comment by Ashrockzzz2003** [comment]
Hi @RD-Tarun ,
Thanks for volunteering. You can work on it.
